M48
; DRILL file {KiCad 7.0.1-0} date 2023 October 30, Monday 18:23:19
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-30T18:23:19-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X138.938Y-53.34
X138.938Y-122.174
X197.993Y-53.721
X198.374Y-121.92
T0
M30
